// Define your own mock data here:
export const standard = (/* vars, { ctx, req } */) => ({
  weatherReport: {
    id: '42',
    worldCity: {
      id: '33',
      city: 'Boston',
      adminName: 'Massachusetts',
      country: 'United States',
    },
    worldCityId: '33',
    headline: 'Windy',
    description: 'So much wind',
    icon: 'a',
    tempFahrenheit: 1,
    feelsLikeFahrenheit: 1,
    tempMinFahrenheit: 1,
    tempMaxFahrenheit: 1,
    tempCelcius: 1,
    feelsLikeCelcius: 1,
    tempMinCelcius: 1,
    tempMaxCelcius: 1,
    temp: 1.1,
    feelsLike: 1.1,
    tempMin: 1.1,
    tempMax: 1.1,
    pressure: 1,
    humidity: 1,
    windSpeed: 1.1,
    windDegrees: 1,
    sunrise: new Date().toISOString(),
    sunset: new Date().toISOString(),
  },
})
